version: "3.9"

services:
  db:
    image: mariadb:10.11
    container_name: grow_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: growanalitics
      MYSQL_USER: prisma
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - grow_network

  server:
    build: ./server
    container_name: grow_server
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./server:/app
    networks:
      - grow_network
    command: >
      sh -c "
      npx prisma migrate deploy &&
      node src/server.js
      "

  client:
    build: ./client
    container_name: grow_client
    restart: always
    env_file:
      - .env
    ports:
      - "5173:5173"
    depends_on:
      - server
    volumes:
      - ./client:/app
    networks:
      - grow_network

volumes:
  db_data:

networks:
  grow_network:
    driver: bridge
